# 차원축소 Assignment1

# ''' ? ''' 이 있는 부분을 채워주세요 

참고하셔야 하는 함수들은 링크 달아드렸으니 들어가서 확인해보세요

무작정 빈칸 채우기가 아니라 꼭 차원축소 과정을 이해하시면서 과제를 진행하시면 좋겠습니다!!!

또 질문은 언제나 환영이니 과제하다가 궁금하신것 있으시면 자유롭게 물어보세요!!

# 1) PCA의 과정 차근차근 밟아보기

In [1]:
#기본 모듈 불러오기
import numpy as np
import numpy.linalg as lin
import matplotlib.pyplot as plt
import pandas as pd
import random

In [2]:
#설명변수 x1, x2, x3
x1 = [95, 91, 66, 94, 68, 63, 12, 73, 93, 51, 13, 70, 63, 63, 97, 56, 67, 96, 75, 6]
x2 = [56, 27, 25, 1, 9, 80, 92, 69, 6, 25, 83, 82, 54, 97, 66, 93, 76, 59, 94, 9]
x3 = [57, 34, 9, 79, 4, 77, 100, 42, 6, 96, 61, 66, 9, 25, 84, 46, 16, 63, 53, 30]

In [3]:
#   설명변수들을 하나의 행렬로
X = np.stack((x1,x2,x3),axis=0)

In [4]:
X = pd.DataFrame(X.T,columns=['x1','x2','x3'])

In [5]:
X

x1  x2   x3
0   95  56   57
1   91  27   34
2   66  25    9
3   94   1   79
4   68   9    4
5   63  80   77
6   12  92  100
7   73  69   42
8   93   6    6
9   51  25   96
10  13  83   61
11  70  82   66
12  63  54    9
13  63  97   25
14  97  66   84
15  56  93   46
16  67  76   16
17  96  59   63
18  75  94   53
19   6   9   30

### 1-1) 먼저 PCA를 시작하기 전 데이터 scaling!!!! 매우 중요합니다!

https://datascienceschool.net/03%20machine%20learning/02.01%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EC%A0%84%EC%B2%98%EB%A6%AC%20%EA%B8%B0%EC%B4%88.html?highlight=%EC%A0%84%EC%B2%98%EB%A6%AC  를 참고하시면 도움이 될거에요

In [6]:
#scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_std = scaler.fit_transform(X)
X_std

array([[ 1.08573604,  0.02614175,  0.30684189],
       [ 0.93801686, -0.86575334, -0.46445467],
       [ 0.01477192, -0.92726334, -1.30282049],
       [ 1.04880625, -1.66538341,  1.04460382],
       [ 0.08863151, -1.41934339, -1.47049366],
       [-0.09601747,  0.76426183,  0.97753455],
       [-1.97943714,  1.13332186,  1.74883111],
       [ 0.2732805 ,  0.42595679, -0.1961776 ],
       [ 1.01187645, -1.5116084 , -1.40342439],
       [-0.53917504, -0.92726334,  1.61469258],
       [-1.94250735,  0.85652683,  0.44098042],
       [ 0.16249111,  0.82577183,  0.60865359],
       [-0.09601747, -0.03536825, -1.30282049],
       [-0.09601747,  1.28709688, -0.76626636],
       [ 1.15959564,  0.33369178,  1.21227698],
       [-0.35452606,  1.16407687, -0.06203907],
       [ 0.05170172,  0.64124181, -1.06807806],
       [ 1.12266584,  0.11840676,  0.50804969],
       [ 0.3471401 ,  1.19483187,  0.17270336],
       [-2.20101593, -1.41934339, -0.5985932 ]])

In [7]:
features = X_std.T

In [8]:
features

array([[ 1.08573604,  0.93801686,  0.01477192,  1.04880625,  0.08863151,
        -0.09601747, -1.97943714,  0.2732805 ,  1.01187645, -0.53917504,
        -1.94250735,  0.16249111, -0.09601747, -0.09601747,  1.15959564,
        -0.35452606,  0.05170172,  1.12266584,  0.3471401 , -2.20101593],
       [ 0.02614175, -0.86575334, -0.92726334, -1.66538341, -1.41934339,
         0.76426183,  1.13332186,  0.42595679, -1.5116084 , -0.92726334,
         0.85652683,  0.82577183, -0.03536825,  1.28709688,  0.33369178,
         1.16407687,  0.64124181,  0.11840676,  1.19483187, -1.41934339],
       [ 0.30684189, -0.46445467, -1.30282049,  1.04460382, -1.47049366,
         0.97753455,  1.74883111, -0.1961776 , -1.40342439,  1.61469258,
         0.44098042,  0.60865359, -1.30282049, -0.76626636,  1.21227698,
        -0.06203907, -1.06807806,  0.50804969,  0.17270336, -0.5985932 ]])

### 1-2) 다음으로 공분산 행렬을 구합니다

https://docs.scipy.org/doc/numpy/reference/generated/numpy.cov.html 를 참고하시면 도움이 될거에요

In [9]:
cov_x = np.cov(features)

In [10]:
cov_x

array([[ 1.05263158, -0.2037104 , -0.12079228],
       [-0.2037104 ,  1.05263158,  0.3125801 ],
       [-0.12079228,  0.3125801 ,  1.05263158]])

### 1-3) 이제 고유값과 고유벡터를 구합니다

실습코드를 참고해주세요

In [27]:
import numpy.linalg as lin

eigenvalues, eigenvectors = lin.eig(cov_x)

In [28]:
eigenvalues

array([1.48756162, 0.94435407, 0.72597904])

In [29]:
eigenvectors

array([[ 0.47018528, -0.85137353, -0.23257022],
       [-0.64960236, -0.15545725, -0.74421087],
       [-0.59744671, -0.50099516,  0.62614797]])

### 1-4) 고유값 분해: 고유값 분해의 곱으로 원래 공분산 행렬을 구해봅니다

https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html 를 참고해주세요

$A = P Λ P^{\prime}$
이 식 기억나죠?

In [30]:
diagonal_mat = np.diag(eigenvalues)
recon = np.dot(np.dot(eigenvectors, diagonal_mat), eigenvectors.T)

In [31]:
recon

array([[ 1.05263158, -0.2037104 , -0.12079228],
       [-0.2037104 ,  1.05263158,  0.3125801 ],
       [-0.12079228,  0.3125801 ,  1.05263158]])

### 1-5) 마지막으로 고유 벡터 축으로 값을 변환합니다


https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html

In [32]:
def new_coordinates(X, eigenvectors):
    combined_eigenvectors = np.concatenate([vec[:, np.newaxis] for vec in eigenvectors.T], axis=1)
    
    return np.dot(X, combined_eigenvectors)

# 2) PCA를 구현해보기

위의 과정을 하나의 함수로 표현해주세요!

1)에서 진행한 과정을 그대로 가져오면 됩니다..! , 

위에서 만든 함수(new_coordinate)도 가져오셔서 사용해도 좋아요!

+하지만 이 함수는 number이라는 인자를 받아서 pca에서 주성분 개수를 고려하도록 합니다!

고유값이 큰 축 순서로 정렬하는 과정 + 주성분 개수 number을 고려해야한다는 점을 유의해서 함수를 정의해주세요


In [33]:
eigenvectors

array([[ 0.47018528, -0.85137353, -0.23257022],
       [-0.64960236, -0.15545725, -0.74421087],
       [-0.59744671, -0.50099516,  0.62614797]])

In [41]:
from sklearn.preprocessing import StandardScaler

def MYPCA(X, number):
    # Scaling
    scaler = StandardScaler()
    features = scaler.fit_transform(X).T
    
    # Covariance
    cov = np.cov(features)
    # eigenvalues, eigenvectors
    eigenvalues, eigenvectors = lin.eig(cov)
    # 고유값 정렬 및 고유값 크기에 따라 고유벡터도 정렬
    sorted_indices = np.argsort(eigenvalues)[::-1]
    sorted_eigenvectors = eigenvectors[:, sorted_indices]
    selected_eigenvectors = sorted_eigenvectors[:, : number]
    #def new_coordinates(X,eigenvectors):
    pca_data = new_coordinates(X, selected_eigenvectors)

    return pca_data

In [42]:
MYPCA(X,3)

# 새로운 축으로 잘 변환되어서 나타나나요?
# 위에서 했던 PCA랑은 차이가 있을 수 있어요 
# 왜냐하면 위에서는 고유값이 큰 축 순서로 정렬을 안했었거든요

array([[ -25.76459322, -118.14281563,  -28.07954506],
       [   4.93440853,  -98.70617271,  -19.96855233],
       [   9.41514902,  -64.58604088,  -28.31957436],
       [  -3.65047618, -119.76318703,   26.85987816],
       [  23.73639094,  -61.29649622,  -20.00808077],
       [ -68.34991312, -104.64973959,  -25.97539951],
       [-113.86586512,  -74.61806491,   -8.6434455 ],
       [ -35.59179944,  -93.91861469,  -42.02996106],
       [  36.24493662,  -83.11645317,  -22.33740768],
       [ -49.61549403,  -95.40201664,   29.64385221],
       [ -84.24883684,  -54.53151206,  -26.5978887 ],
       [ -59.78590706, -105.40932209,  -35.97944043],
       [ -10.83387534,  -66.54018042,  -49.20397885],
       [ -48.32592432,  -81.24076455,  -71.18667863],
       [ -47.45130749, -134.92700444,  -19.080799  ],
       [ -61.56519276,  -85.18021914,  -53.43273629],
       [ -27.42651318,  -76.87270009,  -62.12386301],
       [ -30.8278953 , -122.46653186,  -26.78786006],
       [ -57.46340178, -105.

# 3) sklearn이랑 비교를 해보기

https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html 를 참고하시면 도움이 될거에요

In [43]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)

In [45]:
pca_data = pca.fit_transform(X)
pca_data

array([[ -3.16664013,  25.73014729, -16.63541135],
       [-37.1741275 ,  14.15741953,  -6.85978988],
       [-45.12554929, -19.54144258,   0.56729463],
       [-32.8526285 ,  54.41554996,  25.86035041],
       [-60.85528673, -17.7154455 ,   6.41888372],
       [ 36.27391963,  12.57704836,  -0.16002867],
       [ 73.94814432,  -8.03916032,  37.65034998],
       [  5.12437148,  -2.70272589, -15.72390186],
       [-69.65671671,   1.02480097,  -8.04963357],
       [  8.2551067 ,  31.85408946,  48.5569274 ],
       [ 44.83497197, -32.60949489,  25.33280741],
       [ 29.50965992,   8.95926233, -10.89112437],
       [-21.89034418, -28.82633994, -14.39652588],
       [ 20.18393316, -28.36327038, -32.68698114],
       [ 19.06981735,  43.5771515 , -12.16054826],
       [ 31.01935557, -17.19166064, -16.44540618],
       [ -2.24771829, -26.77360255, -27.00420281],
       [  2.2042456 ,  29.86881558, -16.47726182],
       [ 29.92949938,   0.08950302, -26.98929521],
       [-27.38401373, -40.49064

In [46]:
MYPCA(X,3)

array([[ -25.76459322, -118.14281563,  -28.07954506],
       [   4.93440853,  -98.70617271,  -19.96855233],
       [   9.41514902,  -64.58604088,  -28.31957436],
       [  -3.65047618, -119.76318703,   26.85987816],
       [  23.73639094,  -61.29649622,  -20.00808077],
       [ -68.34991312, -104.64973959,  -25.97539951],
       [-113.86586512,  -74.61806491,   -8.6434455 ],
       [ -35.59179944,  -93.91861469,  -42.02996106],
       [  36.24493662,  -83.11645317,  -22.33740768],
       [ -49.61549403,  -95.40201664,   29.64385221],
       [ -84.24883684,  -54.53151206,  -26.5978887 ],
       [ -59.78590706, -105.40932209,  -35.97944043],
       [ -10.83387534,  -66.54018042,  -49.20397885],
       [ -48.32592432,  -81.24076455,  -71.18667863],
       [ -47.45130749, -134.92700444,  -19.080799  ],
       [ -61.56519276,  -85.18021914,  -53.43273629],
       [ -27.42651318,  -76.87270009,  -62.12386301],
       [ -30.8278953 , -122.46653186,  -26.78786006],
       [ -57.46340178, -105.